version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: car_dealing_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_dealing_system
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: car_dealing_backend
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: car_dealing_frontend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:

